// Sample mailbox dataset for <mz-mailbox>. Kept separate from data.js (the task
// RECORDS) so the inbox stays decoupled from the collection views. Each message
// is a thread: a list of notes between Marzy (the agent), the operator ("You"),
// and teammates or outside contacts. label maps to the cat-* dot classes.

// label -> cat-* dot class (reuses the table category palette; ink + Volt only)
export const LABEL_CAT = {
  Finance: "cat-finance",
  People: "cat-people",
  Ops: "cat-ops",
  Payroll: "cat-payroll",
  Eng: "cat-eng",
  Legal: "cat-legal",
  Clinic: "cat-clinic",
};

// from === "Marzy" renders the spark avatar; "You" is the operator.
export const MESSAGES = [
  {
    id: "m1",
    from: "Marzy",
    email: "marzy@mulholland.inc",
    subject: "June payroll is drafted and ready for review",
    label: "Payroll",
    folder: "inbox",
    unread: true,
    starred: true,
    time: "9:24 AM",
    thread: [
      { from: "Marzy", marzy: true, time: "9:24 AM",
        text: "I pulled this week's 14 timesheets from Gusto and drafted the June payroll run. Two entries are above the auto-approve limit, so I've held the batch for you. Everything else reconciles against last month." },
    ],
  },
  {
    id: "m2",
    from: "Dana Reyes",
    email: "dana@lazarco.com",
    subject: "Re: Q2 invoice reconciliation",
    label: "Finance",
    folder: "inbox",
    unread: true,
    starred: false,
    time: "8:51 AM",
    thread: [
      { from: "Dana Reyes", time: "Yesterday, 4:12 PM",
        text: "Can you take a pass at the Q2 invoices before the board deck? A few from May still look unmatched." },
      { from: "Marzy", marzy: true, time: "Yesterday, 4:15 PM",
        text: "On it — I matched 38 of 41. The remaining three are missing PO numbers; I've flagged them on the Finance board." },
      { from: "Dana Reyes", time: "8:51 AM",
        text: "Perfect, thank you. I'll chase the POs this morning." },
    ],
  },
  {
    id: "m3",
    from: "QuickBooks",
    email: "no-reply@quickbooks.com",
    subject: "Action needed: your connection token expires soon",
    label: "Ops",
    folder: "inbox",
    unread: true,
    starred: false,
    time: "7:30 AM",
    thread: [
      { from: "QuickBooks", time: "7:30 AM",
        text: "Your QuickBooks Online connection for Lazarco Inc. will expire in 3 days. Re-authorize to keep syncing without interruption." },
    ],
  },
  {
    id: "m4",
    from: "Marzy",
    email: "marzy@mulholland.inc",
    subject: "Eligibility checks complete — Tuesday clinic",
    label: "Clinic",
    folder: "inbox",
    unread: false,
    starred: false,
    time: "Yesterday",
    thread: [
      { from: "Marzy", marzy: true, time: "Yesterday, 6:02 PM",
        text: "Ran eligibility for all 23 Tuesday appointments. 21 active, 1 needs a secondary payer, 1 termed — I moved both exceptions to the Clinic board and notified the front desk." },
      { from: "You", you: true, time: "Yesterday, 6:20 PM",
        text: "Great. Did the termed patient get a heads-up?" },
      { from: "Marzy", marzy: true, time: "Yesterday, 6:21 PM",
        text: "Yes — drafted a coverage-lapse note for your review before it goes out." },
    ],
  },
  {
    id: "m5",
    from: "Marcus Lin",
    email: "marcus@lazarco.com",
    subject: "New hire onboarding — start date confirmed",
    label: "People",
    folder: "inbox",
    unread: false,
    starred: true,
    time: "Yesterday",
    thread: [
      { from: "Marcus Lin", time: "Yesterday, 11:40 AM",
        text: "Priya's replacement starts July 1. Can we have the onboarding checklist and payroll setup ready?" },
      { from: "Marzy", marzy: true, time: "Yesterday, 11:42 AM",
        text: "Created the onboarding task and pre-filled the Gusto profile. I'll request the I-9 and direct-deposit details a week out." },
    ],
  },
  {
    id: "m6",
    from: "Sam Okafor",
    email: "sam@lazarco.com",
    subject: "Sikka sync fix is live",
    label: "Eng",
    folder: "inbox",
    unread: false,
    starred: false,
    time: "Mon",
    thread: [
      { from: "Sam Okafor", time: "Mon, 2:15 PM",
        text: "Pushed the fix for the Sikka sync timeout. Can you confirm the nightly run lands clean tonight?" },
      { from: "Marzy", marzy: true, time: "Mon, 2:16 PM",
        text: "Will do — I'll watch the 2 AM run and report back with the record counts." },
    ],
  },
  {
    id: "m7",
    from: "Marzy",
    email: "marzy@mulholland.inc",
    subject: "March books closed",
    label: "Finance",
    folder: "inbox",
    unread: false,
    starred: false,
    time: "Mon",
    thread: [
      { from: "Marzy", marzy: true, time: "Mon, 9:00 AM",
        text: "Closed the March books. Nothing flagged — all accounts reconcile and the variance report is attached to the Finance board." },
    ],
  },
  {
    id: "m8",
    from: "You",
    email: "ops@lazarco.com",
    subject: "Vendor contract — please draft",
    label: "Legal",
    folder: "sent",
    unread: false,
    starred: false,
    time: "Tue",
    thread: [
      { from: "You", you: true, time: "Tue, 10:05 AM",
        text: "Marzy, can you draft the standard vendor contract for the new cleaning service and route it to legal?" },
      { from: "Marzy", marzy: true, time: "Tue, 10:06 AM",
        text: "Drafted from the standard template with their terms filled in. Sent to legal for review — I'll ping you when it's signed." },
    ],
  },
  {
    id: "m9",
    from: "Gusto Support",
    email: "support@gusto.com",
    subject: "Your May payroll filing was accepted",
    label: "Payroll",
    folder: "archive",
    unread: false,
    starred: false,
    time: "Jun 5",
    thread: [
      { from: "Gusto Support", time: "Jun 5, 3:30 PM",
        text: "Your May payroll tax filing for Lazarco Inc. was accepted by all agencies. No further action is required." },
    ],
  },
];
